name: Build Firmware
on:
  push:
    branches: [ chinese ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install PlatformIO
      run: pip install platformio
    - name: Build Standard Firmware
      run: pio run -e m5stack-stamps3
    - name: Build Advanced Firmware
      run: pio run -e cardputer-adv
    - name: Rename binaries
      run: |
        mkdir -p output
        cp .pio/build/m5stack-stamps3/firmware.bin output/ultimate_remote_chinese.bin
        cp .pio/build/cardputer-adv/firmware.bin output/ultimate_remote_chinese_adv.bin
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Ultimate-Remote-Chinese-Firmware
        path: output/*.bin
        retention-days: 30
